'use client';

import { useState, useRef } from 'react';
import { motion, useInView, AnimatePresence } from 'framer-motion';
import { Eye, FileCode2, Copy, Check, Sparkles } from 'lucide-react';

const formatTabs = [
  { key: 'claude', label: 'CLAUDE.md', filename: 'CLAUDE.md' },
  { key: 'cursor', label: '.cursorrules', filename: '.cursorrules' },
  { key: 'replit', label: 'replit.md', filename: 'replit.md' },
] as const;

type FormatKey = (typeof formatTabs)[number]['key'];

const sampleOutputs: Record<FormatKey, string> = {
  claude: `# CLAUDE.md — CVGenie AI Resume Generator

> **Generated by**: GitContextGen Knowledge Engine
> **Repository**: \`cvgenie/cvgenie-app\`
> **Format**: Claude Code / Claude Sonnet

---

## Project Identity
CVGenie is a microSaaS AI-powered resume and cover letter generator.
It uses AI Engine to produce ATS-optimized resumes from uploaded
PDFs and pasted job descriptions. React 18 + Express + FastAPI hybrid.

## Verified Execution Commands
\`\`\`yaml
Dev Server:       npm run dev          # Starts Vite dev server (port 5173)
API Server:       npx tsx server/      # Express API on port 5000
Production Build: npm run build        # Vite production bundle
Type Check:       npx tsc --noEmit     # Full TypeScript validation
\`\`\`
Evidence: package.json#scripts (verified)

## Architecture & Module Boundaries
\`\`\`
client/
├── src/
│   ├── components/         # UI components (shadcn/ui + Radix primitives)
│   │   ├── app-shell/      # SaaS dashboard shell with sidebar nav
│   │   ├── ui/             # Button, Card, Dialog, Toast, etc.
│   │   └── landing/        # Marketing page components
│   ├── hooks/              # Custom React hooks (useIntersectionLoader)
│   ├── pages/              # Route pages (Dashboard, Generator, ATS Score)
│   ├── content/blog/       # Static blog posts data (zero DB cost)
│   └── lib/                # Utility functions and API client
server/
├── routes.ts               # AI Engine calls, /api/generate endpoint
├── documentGenerator.ts    # PDF/DOCX/TXT conversion with watermarks
├── documentParser.ts       # Resume text extraction (PDF/DOCX/TXT)
└── database/
    └── cache.ts            # TTL-based in-memory cache for DB optimization
\`\`\`

## Protected Files — DO NOT MODIFY
| File | Purpose |
|:-----|:--------|
| server/routes.ts | AI Engine integration, ATS formatting, generation endpoint |
| server/documentGenerator.ts | PDF/DOCX/TXT output with free-tier watermarks |
| server/documentParser.ts | Resume parsing via pdfplumber (Python) |

These files handle core AI generation. Any change requires full
end-to-end testing before deployment.

## Safety & Edit Boundaries
- NEVER expose \`.env\` values (ANTHROPIC_API_KEY, CLERK_SECRET_KEY)
- NEVER modify files in \`dist/\`, \`node_modules/\`, or Python \`__pycache__/\`
- NEVER change AI model names or prompt templates unless explicitly asked
- NEVER remove free-tier watermark logic from documentGenerator.ts

## Coding Standards
- React functional components with TypeScript interfaces for all props
- Forms: React Hook Form + Zod schema validation
- State: TanStack React Query with staleTime: 30000 to reduce refetches
- Auth: Clerk (@clerk/clerk-react for frontend, @clerk/express for API)
- Routing: Wouter (lightweight, client-side)
- Styling: Tailwind CSS + shadcn/ui component library`,

  cursor: `# .cursorrules — CVGenie AI Resume Generator

You are an expert full-stack developer working on CVGenie, a microSaaS
application that generates ATS-optimized resumes and cover letters using
the Claude Sonnet 5 & Opus 5 AI Engine. The app has a React + Vite frontend and Express +
FastAPI hybrid backend.

## Tech Stack
- Frontend: React 18, TypeScript, Vite, Tailwind CSS, shadcn/ui
- Backend: Node.js, Express.js, FastAPI (Python for PDF processing)
- Auth: Clerk (OAuth, session management, usage tracking)
- AI: Claude Sonnet 5 for resume optimization and cover letter generation
- State: TanStack React Query, React Hook Form + Zod
- Routing: Wouter (lightweight client-side router)
- Database: Drizzle ORM + Neon PostgreSQL (with in-memory cache layer)

## Project Structure
- client/src/components/   → UI components (shadcn/ui, app-shell, landing)
- client/src/pages/        → Route pages (Dashboard, Generator, ATS, Blog)
- client/src/hooks/        → Custom hooks (useIntersectionLoader, etc.)
- server/routes.ts         → API endpoints, Claude Code & AI integration
- server/documentGenerator.ts → PDF/DOCX/TXT file generation
- server/documentParser.ts → Resume upload & text extraction
- server/database/cache.ts → TTL-based DB query caching

## Critical Rules
1. NEVER modify server/routes.ts, documentGenerator.ts, or
   documentParser.ts during UI updates or bug fixes.
2. After any change to protected files, run a full end-to-end
   generation test (upload PDF → generate resume → download).
3. Use TypeScript strict mode. Avoid \`any\` types.
4. All forms must use React Hook Form with Zod validation schemas.
5. TanStack Query hooks must set staleTime: 30000 to prevent
   unnecessary refetches on component mount.

## Auth & Usage Limits
- Free tier: 3 generations per session (tracked via Clerk)
- Pro tier: Unlimited generations
- Subscription status cached with 120s TTL to reduce DB queries
- UPSERT pattern for subscription writes (single query, no SELECT+UPDATE)

## File Processing Flow
1. User uploads PDF → Multer middleware handles multipart/form-data
2. pdfplumber (Python/FastAPI) extracts text from PDF
3. AI Engine optimizes content for ATS compatibility
4. documentGenerator.ts converts to PDF/DOCX/TXT with watermarks

## Performance Patterns
- Lazy load below-fold sections with useIntersectionLoader hook
- Disable animations on mobile (<768px) and prefers-reduced-motion
- Blog is fully static (zero DB queries, content bundled by Vite)
- DB queries use explicit column lists (no SELECT *)
- Indexes on: user_id, created_at, session_id, dodo_customer_id

## Protected Paths — DO NOT EDIT
- dist/, node_modules/, __pycache__/
- .env, .env.local (ANTHROPIC_API_KEY, CLERK_SECRET_KEY)
- Database migration files (auto-generated by Drizzle)`,

  replit: `# CVGenie
AI-powered resume and cover letter generator that creates ATS-optimized
documents from uploaded PDFs and pasted job descriptions.

## Run & Operate
- \`npm run dev\` — start Vite dev server on port 5173
- \`npx tsx server/\` — start Express API server on port 5000
- \`npm run build\` — production build via Vite
- \`npx tsc --noEmit\` — full TypeScript type check
Required env: ANTHROPIC_API_KEY, CLERK_SECRET_KEY,
  VITE_CLERK_PUBLISHABLE_KEY, DATABASE_URL

## Stack
- Frontend: React 18, TypeScript, Vite, Tailwind CSS, shadcn/ui (Radix)
- Backend: Node.js + Express.js (primary API), FastAPI/Python (PDF parsing)
- Auth: Clerk (OAuth, sessions, usage limits)
- AI: Claude Sonnet 5 (resume optimization, cover letter generation, ATS formatting)
- DB: Drizzle ORM + Neon PostgreSQL, in-memory TTL cache layer
- State: TanStack React Query, React Hook Form + Zod validation
- Routing: Wouter (client-side), Express Router (server-side)
- File Processing: Multer (uploads), pdfplumber (PDF extraction)

## Where things live
- \`client/src/components/\`: UI components — shadcn/ui primitives,
  app-shell (sidebar + top bar), and landing page sections.
- \`client/src/pages/\`: Route pages — Dashboard, Generator, ATS Score,
  Resume History, Blog listing and post pages.
- \`client/src/hooks/\`: Custom hooks — useIntersectionLoader for lazy loading.
- \`client/src/content/blog/\`: Static blog post data (zero DB cost).
- \`server/routes.ts\`: AI Engine calls, /api/generate endpoint,
  resume optimization and ATS formatting logic.
- \`server/documentGenerator.ts\`: Converts AI text to downloadable
  PDF/DOCX/TXT files with free-tier watermarks.
- \`server/documentParser.ts\`: Extracts text from uploaded resumes.
- \`server/database/cache.ts\`: TTL-based Map cache for subscription
  status (120s), resume history (60s), individual resumes (300s).

## Architecture decisions
- Hybrid backend: Express handles API routes and auth, FastAPI handles
  CPU-intensive PDF text extraction via pdfplumber.
- Two-step AI generation: first pass optimizes content, second pass
  enforces ATS-compliant formatting — ensures both quality and structure.
- In-memory cache layer sits between API routes and Neon PostgreSQL to
  minimize serverless compute costs (cache invalidated on writes).
- Static blog: all content bundled into frontend JS by Vite, zero
  server endpoints or database queries needed.
- UPSERT for subscription writes eliminates SELECT+INSERT/UPDATE race.

## Product
Freemium microSaaS — free users get 3 AI generations with watermarked
documents, Pro users get unlimited generations and clean exports.
Features: PDF resume upload, job description paste, ATS keyword
extraction, inline editing before download, multi-format export
(PDF/DOCX/TXT), SaaS dashboard with usage stats and resume history.

## User preferences
- Use functional TypeScript components with explicit props interfaces.
- All forms use React Hook Form with Zod schemas for validation.
- TanStack Query hooks must set staleTime: 30000 on subscription and
  resume queries to prevent refetching on every component mount.
- Mobile: disable animations below 768px, support prefers-reduced-motion.
- Simple, everyday language in user-facing copy.

## Gotchas
- Stripe webhook handler requires raw body parsing — don't add JSON
  middleware to that route or signature verification will fail.
- pdfplumber runs in Python/FastAPI — Node.js cannot call it directly,
  must go through the FastAPI endpoint.
- Free-tier watermark logic in documentGenerator.ts is intentional —
  don't remove it thinking it's a bug.
- Environment variables prefixed VITE_ are exposed to the browser.
- Always run full end-to-end generation test after touching any
  file in the server/ directory.

## Pointers
- Generation flow: Upload → documentParser → AI Engine → documentGenerator → Download
- Auth flow: Clerk React → Clerk Express middleware → usage limit check → proceed
- Cache invalidation: Subscription cache cleared on webhook + manual update;
  Resume cache cleared on insert/delete operations.
- DB indexes: user_id, created_at, session_id, dodo_customer_id`,
};

export default function OutputPreviewSection() {
  const [activeTab, setActiveTab] = useState<FormatKey>('claude');
  const [copied, setCopied] = useState(false);
  const [showGuide, setShowGuide] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: '-80px' });

  const handleCopy = () => {
    if (typeof navigator !== 'undefined' && navigator.clipboard) {
      navigator.clipboard.writeText(sampleOutputs[activeTab])
        .then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        })
        .catch((err) => console.warn('Clipboard write error:', err));
    }
  };

  return (
    <section className="flex flex-col items-center justify-center w-full max-w-7xl mx-auto px-4 sm:px-6 py-28 md:py-36 bg-black text-white">
      <div ref={ref} className="w-full flex flex-col items-center justify-center">

        {/* Section Header */}
        <div className="w-full max-w-3xl mx-auto flex flex-col items-center text-center mb-12">
          <div className="w-fit inline-flex items-center justify-center gap-2 px-4 py-2 rounded-full bg-white/[0.04] text-xs font-mono text-white/80 mb-6">
            <Eye className="w-3.5 h-3.5 text-cyan-400" /> See What You Get
          </div>
          <h2 className="text-3xl sm:text-5xl font-extrabold tracking-tight mb-6 text-white leading-tight text-center">
            Real Output From a{' '}
            <span className="font-serif italic font-normal text-white/80">Real Repository.</span>
          </h2>
          <p className="text-base sm:text-lg text-white/50 max-w-2xl mx-auto mb-6">
            This is what GitContextGen generates from a single GitHub URL.
            Detailed architecture, verified commands, safety boundaries, and coding standards — not vague summaries.
          </p>

          {/* Non-Coder Explainer Banner Toggle */}
          <div className="p-4 rounded-xl bg-white/[0.03] border border-white/10 max-w-2xl w-full text-left space-y-3 font-mono text-xs">
            <div className="flex items-center justify-between">
              <span className="text-cyan-400 font-bold flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-cyan-400" /> Non-Coder Workflow (3 Steps):
              </span>
              <button
                onClick={() => setShowGuide(!showGuide)}
                aria-expanded={showGuide}
                className="px-2.5 py-1 rounded bg-white/10 hover:bg-white/20 text-white text-[11px] transition-all"
              >
                {showGuide ? 'Hide Plain-English Guide' : '💡 Show Plain-English Guide'}
              </button>
            </div>
            {showGuide && (
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 pt-2 border-t border-white/10 text-[11px] text-white/70">
                <div><strong className="text-cyan-300">1. Copy Output:</strong> Click Copy below</div>
                <div><strong className="text-indigo-300">2. Drop in Folder:</strong> Save file in repo</div>
                <div><strong className="text-emerald-300">3. AI Reads Spec:</strong> Flawless code</div>
              </div>
            )}
          </div>
        </div>

        {/* Format Tab Switcher */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5, delay: 0.1 }}
          role="tablist"
          aria-label="Target AI Specification Formats"
          className="flex items-center gap-2 p-1.5 rounded-xl bg-white/[0.03] border border-white/[0.06] mb-6 overflow-x-auto no-scrollbar max-w-full"
        >
          {formatTabs.map((tab) => (
            <button
              key={tab.key}
              role="tab"
              aria-selected={activeTab === tab.key}
              onClick={() => setActiveTab(tab.key)}
              className={`px-4 py-2 rounded-lg text-sm font-mono transition-all duration-200 shrink-0 ${
                activeTab === tab.key
                  ? 'bg-white/[0.08] text-white border border-white/[0.1]'
                  : 'text-white/40 hover:text-white/70 border border-transparent'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </motion.div>

        {/* Output Preview Window */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="w-full max-w-4xl"
        >
          <div className="rounded-2xl bg-white/[0.02] border border-white/[0.06] shadow-2xl overflow-hidden">
            {/* Window Title Bar */}
            <div className="flex items-center justify-between px-5 py-3.5 border-b border-white/[0.06] bg-white/[0.01]">
              <div className="flex items-center gap-3">
                <div className="flex gap-2">
                  <span className="w-3 h-3 rounded-full bg-red-500/80" />
                  <span className="w-3 h-3 rounded-full bg-amber-400/80" />
                  <span className="w-3 h-3 rounded-full bg-emerald-400/80" />
                </div>
                <span className="text-xs font-mono text-white/40 ml-2">
                  <FileCode2 className="w-3.5 h-3.5 inline mr-1.5 -mt-0.5" />
                  {formatTabs.find(t => t.key === activeTab)?.filename}
                </span>
              </div>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-mono text-white/40 hover:text-white/80 hover:bg-white/[0.04] transition-all"
              >
                {copied ? (
                  <><Check className="w-3.5 h-3.5 text-emerald-400" /> Copied</>
                ) : (
                  <><Copy className="w-3.5 h-3.5" /> Copy</>
                )}
              </button>
            </div>

            {/* Scrollable Code Content */}
            <div className="relative">
              <AnimatePresence mode="wait">
                <motion.div
                  key={activeTab}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.25 }}
                >
                  <pre className="p-6 sm:p-8 overflow-x-auto overflow-y-auto max-h-[520px] text-sm sm:text-[13px] leading-relaxed font-mono text-white/70 whitespace-pre-wrap break-words scrollbar-thin">
                    {sampleOutputs[activeTab]}
                  </pre>
                </motion.div>
              </AnimatePresence>

              {/* Bottom Fade Gradient */}
              <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-black/90 via-black/50 to-transparent pointer-events-none" />
            </div>

            {/* Bottom Bar */}
            <div className="flex items-center justify-between px-5 py-3.5 border-t border-white/[0.06] bg-white/[0.01]">
              <span className="text-xs font-mono text-white/30">
                {sampleOutputs[activeTab].split('\n').length} lines • Evidence-verified specification
              </span>
              <div className="flex items-center gap-1.5 text-xs font-mono text-emerald-400/70">
                <Sparkles className="w-3.5 h-3.5" /> Generated from GitHub URL
              </div>
            </div>
          </div>
        </motion.div>

        {/* Caption */}
        <motion.p
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
          transition={{ duration: 0.5, delay: 0.5 }}
          className="mt-6 text-xs text-white/30 font-mono text-center max-w-lg"
        >
          Sample output for <span className="text-white/50">cvgenie/cvgenie-app</span>.
          Your repository produces a unique specification based on its actual file structure and dependencies.
        </motion.p>
      </div>
    </section>
  );
}
